version: '3.7'
services:
  web:
    image: nginx:latest
    restart: always
    networks:
      - webdev
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.gemstracker.rule=Host(`gemstracker.test`)"
    ports:
      - "8080:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
      #- ../pulse_ls:/app/public/ls
      #- ./docker/ls/config.php:/app/public/ls/application/config/config.php
    links:
      - php

  php:
    build:
      context: docker/php
      dockerfile: php.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    networks:
      - webdev
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./:/app
    env_file:
      - .env

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - webdev
    environment:
      - MYSQL_ROOT_PASSWORD=test123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init/01-gems-db-init.sql:/docker-entrypoint-initdb.d/01-gems-db-init.sql

  traefik:
     image: traefik:v2.6
     command: --api.insecure=true --providers.docker
     networks:
       - webdev
     ports:
       - "80:80"
       - "8082:8080"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  adminer:
     build:
       context: ./docker
       dockerfile: adminer.Dockerfile
     restart: always
     labels:
       - "traefik.http.routers.adminer.rule=Host(`adminer.test`)"
     networks:
       - webdev
     environment:
       ADMINER_DEFAULT_SERVER: mysql

  mailhog:
     container_name: mailhog
     image: mailhog/mailhog
     restart: always
     labels:
       - "traefik.http.routers.mailhog.rule=Host(`mailhog.test`)"
       - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
     networks:
       - webdev

networks:
  webdev:
    name: webdev

volumes:
  mysql_data:
